modLoader="javafml"
loaderVersion="[41,)"
license="Apache License 2.0"
[[mods]]
modId="randomworldname"
version="${version}"
displayName="Random World Name"
authors="smbarbour"
description='''
Generates a random default world name when creating a new world
'''
